config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :meetings do
  	 resources :comments
  end
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  get 'active-sessions', to: "meetings#active_sessions"
  get  'roles/:role', to: "users#fetchrole"
  resources :users , only: [:index]
  #mount_ember_app :frontend, to: "/frontend"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

#Rails.application.routes.draw do
#  mount_ember_app :frontend, to: "/"
#end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :meeting
  belongs_to :user
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  has_many:comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :meetings, dependent: :destroy #need to check this afters
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name,:role,:description])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end

  def cors_preflight_check
  if request.method == :options
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = '*'
    headers['Access-Control-Max-Age'] = '1728000'
    render :text => '', :content_type => 'text/plain'
  end
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	skip_before_action :verify_authenticity_token
	before_action :authenticate_user!
	before_action :set_comment, only:[:edit, :update, :show, :destroy]
	before_action :set_meeting

	def new
		@comment = comment.new
	end 

	def create
		@comment = @meeting.comments.create(params[:comment].permit(:reply, :meeting_id))
	    if @comment.save
	       puts 'comment:'+ @comment.reply+' true'
	    else 
	       puts 'comment:'+ @comment.reply+' false'
	    end
		@comment.user_id = current_user.id
		puts 'comment:'+@comment.reply
		respond_to do |format|
          if @comment.save
			format.html { redirect_to meeting_path(@meeting)}
			format.js #render create.js.erb
		  else
			format.html { redirect_to meeting_path(@meeting), notice: "your comment did not save"}
		  end
	    end
	end

	def destroy
		@comment = @meeting.comment.find(params[:id]);
		@comment.destroy
		redirect_to meeting_path(@meeting)
	end

	private

	  def set_meeting
	  	@meeting = Meeting.find(params[:meeting_id])
	  end

	  def set_comment
	  	@comment  = Comment.find(params[:id])
	  end

	  def comment_params
	  	params.require(comment).permit(:reply)
	  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  def index
    if(current_user.admin?)
      @meetings = Meeting.all
    else
      @meetings = current_user.meetings.where(user_id: current_user)
    end
  end

  # GET /meetings/1 or /meetings/1.json
  def show
    @comment = Comment.new
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    puts meeting_params.to_yaml
    @meeting.user_id = current_user.id

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: "Meeting was successfully created." }
        format.json { render :show, status: :created, location: @meeting }
        MeetingMailer.with(meeting: @meeting, user: current_user).meeting_scheduled.deliver_now;
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "Meeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def active_sessions
    @active_sessions = Meeting.where("end_time > ?",Time.now);
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time, :user_id, :meeting_with_user)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def fetchrole
		puts params[:role]
		@users = User.where("role = ?", params[:role]);
		render json: @users
	end

	def must_be_admin
		unless current_user.admin?
		  redirect_to meetings_path, alert: 'you dont have access to this page'
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def readable_time(time)
		time.strftime("%b %d,%I:%M%P")
	end

	def author_of(record)
	    user_signed_in? && current_user.id == record.user_id
	end

	def admin?
		user_signed_in? && current_user.admin?
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div class="flex items-start p-4 mt-4 border rounded">
  <div class="flex-1 pl-4 flex items-start justify-between">
    <div class="leading-normal">
      <p class="text-grey-dark text-xs"><%= comment.user.first_name %> commented <%= time_ago_in_words(comment.created_at) %> ago</p>
      <div class="text-grey-darkest"><%= sanitize comment.reply %></div>
    </div>

    <% if author_of(comment) %>
      <%= link_to "Delete", meeting_comment_path(comment.meeting, comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-destroy" %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<p class="text-sm text-grey-dark my-2">comment as <%= current_user.first_name %></p>
<%= form_for([@meeting, @comment], remote: true) do |f| %>
  <div class="relative">
    <%= f.text_field :reply, class: "input h-64 border border-grey-light resize-none", placeholder: "Add any notes or replies here" %>

    <trix-editor input="comment_reply" id="comment_reply_trix" class="h-32 p-4"></trix-editor>

    <%= f.submit class: "btn btn-small btn-secondary block w-full text-center mt-2 lg: mt-0 lg:text-left lg:absolute lg:pin-b lg:pin-r lg:mb-2 lg:mr-2 lg:w-auto lg:inline-flex" %>
  </div>
<% end %>

app/views/comments/create.js.erb
var comments = document.getElementById("comments");
var commentField = document.getElementById("comment_reply");
var trixField = document.getElementById("comment_reply_trix");
comments.insertAdjacentHTML("beforeend", "<%= escape_javascript(render(@comment)) %>");
commentField.value = "";
trixField.innerHTML = "";

app/views/home/index.html.erb
<div class="py-10 lg:py-20 px-4 border-b border-grey-light mb-4 text-indigo-darker">
  <div class="container m-auto text-center">
    <h1 class="text-xl lg:text-3xl">Welcome to <%= Rails.configuration.application_name %>!</h1>
    <p class="lead my-2 max-w-md m-auto leading-normal text-grey-darker text-lg mb-4">A-Z consultation 24/7</p>

    <% unless user_signed_in? %>
    <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-primary my-3" %>
    <% else %>
    <%= link_to "Schedule a new session", "http://localhost:4200/consultationoptions", class:"btn btn-primary my-3" %>
    <% end %>
  </div>
</div>


<div class="max-w-lg m-auto">
  <div class="py-10 lg:py-16 px-4 flex flex-wrap items-center justify-between">

    <div class="lg:w-1/2 w-full mb-4 lg:mb-0">
      <h3 class="mb-1">Become a pro in no time</h3>
      <p class="leading-normal">Get consultation in any field from experienced, become an expert in that</p>
    </div>

    <div class="lg:w-1/2 w-full text-center">
      <%= image_tag 'teacher.svg', alt: "Become a pro", width: 400 %>
    </div>
  </div>

  <div class="py-10 lg:py-16 px-4 flex flex-wrap items-center justify-between">
    <div class="lg:w-1/2 w-full mb-4 lg:mb-0">
      <%= image_tag 'move-forward.svg', alt: "Move forward", width: 320 %>
    </div>

    <div class="lg:w-1/2 w-full">
      <h3 class="mb-1">Move foward with your skills</h3>
      <p class="leading-normal">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur commodi similique nihil tempore, possimus, sequi unde illum, officia impedit maxime aut obcaecati. Eligendi officia ipsam et optio, tempore.</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Rails.configuration.application_name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v3/", 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, name: "stripe-public-key", content: Rails.application.credentials.stripe_publishable_key %>
    <%#= javascript_pack_tag 'purchases', 'data-turbolinks-track': 'reload' %>
  </head>

 <body class="bg-grey-lighter">
  <% flash.each do |type, message| %>
    <% if type == "alert" %>
      <div class="bg-red-light">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
    <% if type == "notice" %>
      <div class="bg-green-light">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
  <% end %>

    <header class="bg-white">
      <nav class="flex items-center justify-between flex-wrap bg-grey-lightest p-4 text-grey-darker border-b border-grey-light">
        <div class="flex items-center flex-no-shrink mr-6">
          <%= link_to root_path, class:"link text-xl tracking-tight font-semibold" do %>
            <svg viewBox="0 0 20 20" width="20" height="20" class="fill-current text-grey-darker"><path d="M13 8V0L8.11 5.87 3 12h4v8L17 8h-4z"></path></svg>
            <%= Rails.configuration.application_name %>
          <% end %>
        </div>
        <div class="block lg:hidden">
          <button class="flex items-center px-3 py-2 border rounded text-grey border-grey hover:text-grey-dark hover:border-grey-dark">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
          </button>
        </div>
        <div class="w-full block lg:flex-1 lg:flex items-center text-center lg:text-left">
          <div class="w-full block lg:flex lg:flex-row lg:flex-1 mt-2 lg:mt-0 text-center lg:text-left lg:justify-end">
            <% unless user_signed_in? %>
            <%= link_to "Login", new_user_session_path, class:"btn btn-default mr-2" %>
            <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-default" %>
            <% else %>
            <%= link_to "Dashboard", meetings_path, class: "btn btn-default mr-2" %>
            <%= link_to "Schedule new session", "http://localhost:4200/consultationoptions", class: "btn btn-default mr-2" unless admin? %>
            <%= link_to "Users", users_path, class: "btn btn-default mr-2" if admin? %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-default mr-2" %>
            <% end %>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/meetings/_calendar.html.erb
<%= month_calendar events: meetings do |date, meetings| %>
  <%= date %>
  <% meetings.each do |meeting| %>
    <div>
      <%= link_to meeting.name, meeting, class: "link" %>
    </div>
  <% end %>
<% end %>

app/views/meetings/_form.html.erb
<div class="p-10 bg-white border border-grey-light rounded">
<%= form_with(model: meeting, local: true, class: "meeting-form") do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3 class="mb-4">Meeting Information</h3>

  <div class="mb-6">
    <%= form.label :name, class: "label" %>
    <%= form.text_field :name, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :start_time, class: "label" %>
    <div class="flex items-center justify-between max-w-md">
      <%= form.datetime_select :start_time, { start_day: Date.today, start_year: Date.today.year, minute_step: 15 }, { class: "select py-2 px-2 mr-2" } %>
    </div>
  </div>

  <div class="field">
    <%= form.label :end_time, class: "label" %>
    <div class="flex items-center justify-between max-w-md">
      <%= form.datetime_select :end_time, { start_day: Date.today, start_year: Date.today.year, minute_step: 15 }, { class: "select py-2 px-2 mr-2" } %>
    </div>
  </div>

  <hr class="border" />

  <%#= render "payment_form" %>

  <%= form.submit class: "btn btn-primary text-base py-3 px-5" %>

<% end %>
</div>

app/views/meetings/_meetings_cta.html.erb
<div class="max-w-md my-10 m-auto p-12 lg:p-16 bg-white rounded border border-grey-light text-center shadow">
  <%= image_tag "schedule.svg", alt: "schedule", width: 300, class: "mb-4" %>
  <h1 class="text-indigo-darker text-2xl mb-6">It looks like you haven't scheduled a session yet</h1>
  <%= link_to "Schedule a new session", new_meeting_path, class: "btn btn-primary py-3 px-5" %>
</div>

app/views/meetings/_meetings_landing.html.erb
<script>
  function onTabClick(event) {
    // const activeTabs = document.querySelectorAll('.active');
    // console.log("on onTabClick");
    // activeTabs.forEach(function(tab) {
    //   tab.classList.toggle('active');
    // });


    // event.target.parentElement.classList.add('active');

    // event.preventDefault();

    // // show and hide tab panels
     var element = document.getElementById("calendar");
     var meetings = document.getElementById("all-meetings");
    // tabPanel.classList.toggle('active');
    var tabPanel = document.getElementById(event.target.href.split("#")[1]);

     console.log(tabPanel.id+" "+element.id);
     if((tabPanel.id == element.id && element.style.display != "block") || (tabPanel.id == meetings.id && meetings.style.display != "block")) {
       if (element.style.display === "none") {
         element.style.display = "block";
        } else {
         element.style.display = "none";
        }

        if (meetings.style.display === "none") {
         meetings.style.display = "block";
        } else {
         meetings.style.display = "none";
        }
     }
  }
</script>
<nav class="bg-white mb-4 shadow rounded">
  <ul id="nav-tab" class="tabs list-reset flex">

    <li id="x" data-tab="calendar" onClick = "onTabClick(event)">
      <%= link_to "#calendar", class: "tab flex items-center" do %>
       <svg viewBox="0 0 20 20" width="16" height="16" class="fill-current text-grey-light mr-2"><title>calendar</title><path d="M1 4c0-1.1.9-2 2-2h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4zm2 2v12h14V6H3zm2-6h2v2H5V0zm8 0h2v2h-2V0zM5 9h2v2H5V9zm0 4h2v2H5v-2zm4-4h2v2H9V9zm0 4h2v2H9v-2zm4-4h2v2h-2V9zm0 4h2v2h-2v-2z"></path></svg>
       Calendar
      <% end %>
    </li>

     <li id="y" data-tab="all-meetings" onClick = "onTabClick(event)">
      <%= link_to "#all-meetings", class: "tab flex items-center" do %>
        <svg viewBox="0 0 20 20" class="fill-current text-grey-light mr-2" width="16" height="16"><title>coffee</title><path d="M4 11H2a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2h2V1h14v10a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4zm0-2V5H2v4h2zm-2 8v-1h18v1l-4 2H6l-4-2z"></path></svg>
      All Meetings
      <% end %>
    </li>

  </ul>
</nav>

<div class="bg-white p-10 border rounded">
  <div id="all-meetings">

     <h1>Meetings</h1>

     <% meetings.each do |meeting| %>
        <div class="flex flex-wrap items-center justify-start p-4 border-b border-grey-light mb-6">
          <div class="flex-1 flex justify-between">
            <div>
              <%= link_to meeting.name, meeting, class: "link mr-4" %>
            </div>
            <div>
              <%= readable_time(meeting.start_time) %> &ndash;
              <%= readable_time(meeting.end_time) %>
            </div>
          </div>
        </div>

        <%= button_to "Cancel Meeting", meeting, method: :delete, data: { confirm: "Are you sure? There are no refunds." }, class: "btn btn-destroy ml-4" %>
     <% end %>
  </div>

  <div id="calendar" onClick = "onTabClick(event)">
    <h2>Meeting Calendar</h2>
    <div id="meeting-calendar">
      <%= render "calendar", meetings: meetings  %>
    </div>
  </div>
</div>
<script>
  // document.addEventListener("turbolinks:load", () => {
  // console.log("in addEventListener");
  // const tabElements = document.querySelectorAll('#nav-tab .tab');
  var element = document.getElementById("calendar");
  var meetings = document.getElementById("all-meetings");

  element.style.display = "block"
  meetings.style.display = "none";


//   if(tabElements != null) {
//     tabElements.forEach(function(tab) {
//       tab.addEventListener('click', (event) => {
//         onTabClick(event);
//       });
//     });
//   }
// });
</script>

app/views/meetings/_payment_form.html.erb
<h3 class="pt-5 mb-4">Payment</h3>
  <div class="mb-6 relative mt-2">
    <label for="card-element" class="label">
      Enter credit or debit card. All sessions cost $199 USD.
    </label>

    <div id="card-element" class="input">
      <!-- a Stripe Element will be inserted here. -->
   </div> 
    <!-- used to display Element errors -->
   <div id="card-errors" role="alert"></div>
  </div>

  <% if current_user.stripe_id.present? %>
    <div class="bg-grey-lightest p-5 border border-grey-light rounded mb-6">
      <h4>Previously used card</h4>

      <div class="flex flex-wrap items-center justify-between my-4">
        <div class="w-full lg:w-auto mb-6 lg:mb-0">
          <p class="label">Card Brand</p>
          <p><%= current_user.card_brand %></p>
        </div>
        <div class="w-full lg:w-auto mb-6 lg:mb-0">
          <p class="label">Last 4 Digits</p>
          <p><%= current_user.card_last4 %></p>
        </div>
        <div class="w-full lg:w-auto mb-6 lg:mb-0">
          <p class="label">Exp. Month</p>
          <p><%= current_user.card_exp_month %></p>
        </div>
        <div class="w-full lg:w-auto">
          <p class="label">Exp. Year</p>
          <p><%= current_user.card_exp_year %></p>
        </div>
      </div>
    </div> 

  <% end %> 

app/views/meetings/active_sessions.html.erb
<div class="container m-auto bg-white my-10 border border-grey-light p-10">
  <h1 class="text-indigo-darker">Active Sessions</h1>
  <% if @active_sessions %>
   <% @active_sessions.each do |meeting| %>
    <div class="flex flex-wrap items-center justify-start p-4 border-b border-grey-light mb-6">
      <div class="flex-1 flex justify-between">
        <div>
          <%= link_to meeting.name, meeting, class: "link mr-4" %>
        </div>
        <div>
          <%= readable_time(meeting.start_time) %> &ndash;
          <%= readable_time(meeting.end_time) %>
        </div>
      </div>

      <%= link_to 'Cancel Meeting', meeting, method: :delete, data: { confirm: 'Are you sure? There are no refunds' }, class: "btn btn-destroy ml-4" if admin? %>
    </div>
    <% end %>
    <% end %>
</div>

app/views/meetings/edit.html.erb
<div class="max-w-lg m-auto px-4">
  <h1 class="text-3xl mt-10">Edit sessions</h1>
  <p class="text-lg text-grey-darker mb-6">Modify your consulting session by choosing the best time that works for you below.</p>
  <%= render 'form', meeting: @meeting %>
</div>

app/views/meetings/index.html.erb
<div class="container m-auto my-4">
  <% unless current_user.meetings.any? %>
    <%= render "meetings_cta" %>
  <% else %>
    <%= render "meetings_landing", meetings: @meetings %>
  <% end %>
</div>

app/views/meetings/new.html.erb
<div class="max-w-lg m-auto px-4">
  <h1 class="text-3xl mt-10">Schedule a new session</h1>
  <p class="text-lg text-grey-darker mb-6">Schedule a new consulting session by choosing the best time that works for you below.</p>
  <%= render 'form', meeting: @meeting %>
</div>

app/views/meetings/show.html.erb
<div class="max-w-lg my-10 m-auto">
  <div class="p-10 bg-white border border-grey-light rounded">

    <div class="flex flex-wrap justify-between items-center mb-5">
      <h1><%= @meeting.name %></h1>
      <%= link_to "Cancel Meeting", meeting_path(@meeting), method: :delete, data: { confirm: "Are you sure you want to cancel? "}, class: "btn btn-destroy" if admin? %>
    </div>

    <div class="border p-6 bg-grey-lighter mb-5 flex items-center justify-between">
      <p class="border-2 py-3 px-4 border-indigo rounded-full text-sm text-indigo">
        Start time: <span class="font-bold"><%= readable_time(@meeting.start_time) %></span>
      </p>
      <div class="border-t-2 border-indigo-light border-dashed h-1 flex-1"></div>
      <p class="border-2 py-3 px-4 border-indigo rounded-full text-sm text-indigo">
        End time: <span class="font-bold"><%= readable_time(@meeting.end_time) %></span>
      </p>
    </div>

    <h4>Comments</h4>
    <hr class="border" />

    <% unless user_signed_in? %>
      <div class="bg-grey-lighter rounded p-4 mt-4 text-center">
        <p class="text-sm text-grey-dark"><%= link_to "Login", new_user_session_path, class: "link" %> or <%= link_to "Sign up", new_user_regsitration_path, class: "link" %> to comment.</p>
      </div>
    <% else %>
        <%= render 'comments/form' %>
    <% end %>

    <div id="comments">
      <%= render @meeting.comments %>
    </div>
  </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/_user.html.erb
<div class="flex flex-wrap items-center mb-5 text-indigo-darker">
  <div class="flex-1 flex justify-between items-center">
    <div><h3 class="text-lg"><%= user.name %></h3> <%= user.first_name+" "+user.last_name %> <% if current_user %>(You)<% end %></div>
    <p>Joined on <%= readable_time(user.created_at) %></p>

  </div>
  <%= link_to 'Delete User', users_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-destroy ml-4" if admin? %>
</div>

<% if user.meetings.any? %>
  <div class="block pl-2 border-l border-indigo-light mb-5">
    <p class="text-xs uppercase tracking-loose text-grey-darker pt-1">Upcoming Meetings</p>
    <% user.meetings.each do |meeting| %>
        <%= link_to meeting.name, meeting, class: "link my-2 inline-block" %>
    <% end %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container m-auto bg-white my-10 border border-grey-light p-6">
  <h1 class="text-indigo-darker pb-2 border-b border-grey-light mb-4">Users</h1>
  <%= render @users %>
</div>